<!--
Copyright (c) 2022 Nitro Agility S.r.l.
SPDX-License-Identifier: Apache-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.permguard.example</groupId>
    <artifactId>permguard-check-example</artifactId>
    <version>0.0.1</version>
    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.permguard.pep</groupId>
            <artifactId>permguard</artifactId>
            <version>0.0.1</version>
        </dependency>
    </dependencies>
    <build>
        <sourceDirectory>main/java</sourceDirectory>
    </build>
</project>
